
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // The app connects through DATABASE_URL, which can be a pooled connection in
  // production. Migrations need a direct connection, so the CLI uses
  // DIRECT_URL when it's set. Locally it can be left unset.
  datasource: {
    url: env("DATABASE_URL"),
    directUrl: process.env.DIRECT_URL || undefined,
  },
});
